/*
 * config.h
 * Kyle Isom <coder@kyleisom.net>
 *
 * configuration options for aescrypt
 */
 
/* require at least gnupg 1.4.0 */
#define         GCRYPT_MIN_VERSION      "1.4.0"

/* use secure memory - if defined, should be the size in bytes to allocate
 * for secure memory */
#define 	SECURE_MEM		65535

/* define strength of randomly generated bytes */
#define         RANDOM_STRENGTH         GCRY_VERY_STRONG_RANDOM

/* don't pull in unnecessary gcrypt functions */
#define		GCRYPT_NO_MPI_MACROS	1
#define		GRYPT_NO_DEPRECATED	1

/* for development, pull in debug messages */
#define         DEBUG                   1

